services:
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '32000:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  web:
    build:
      context: .
    environment:
      FLASK_APP: main
      FLASK_DEBUG: 1
    links:
      - mysql_db
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0
    depends_on:
      - mysql_db
    ports:
      - 5000:5000
